apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-frontends-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "micro-frontends-ip"
    networking.gke.io/managed-certificates: "micro-frontends-cert"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - http:
      paths:
      - path: /mf1
        pathType: Prefix
        backend:
          service:
            name: mf1-nextjs-service
            port:
              number: 3000
      - path: /mf1/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: mf1-nextjs-service
            port:
              number: 3000
      - path: /mf2
        pathType: Prefix
        backend:
          service:
            name: mf2-vue-service
            port:
              number: 80
      - path: /mf2/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: mf2-vue-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mf1-nextjs-service
            port:
              number: 3000
