apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microfrontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: mf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mf1-nextjs-service
            port:
              number: 3000
      - path: /blogs
        pathType: Prefix
        backend:
          service:
            name: mf2-vuejs-service
            port:
              number: 80
